In [1]:
import pandas as pd
import os

In [2]:
os.listdir('data/raw')

['attendance.csv',
 'facilities.csv',
 'members.csv',
 'payments.csv',
 'README.md']

In [6]:
facilities_df = pd.read_csv('data/raw/facilities.csv')

In [7]:
facilities_df.isna().sum()

facility_id        0
facility_name      0
capacity           0
hourly_rate_pkr    0
dtype: int64

In [8]:
facilities_df.drop_duplicates()

  facility_id  facility_name  capacity  hourly_rate_pkr
0        F001            Gym        80              500
1        F002  Swimming Pool        60              700
2        F003      Badminton        30              600
3        F004     Basketball        40              500
4        F005       Football        50              800

In [9]:
facilities_df['facility_name']= facilities_df['facility_name'].apply(lambda x :x.lower())

In [103]:
facilities_df

  facility_id  facility_name  capacity  hourly_rate_pkr
0        F001            gym        80              500
1        F002  swimming pool        60              700
2        F003      badminton        30              600
3        F004     basketball        40              500
4        F005       football        50              800

In [10]:
members_df = pd.read_csv('data/raw/members.csv')

In [11]:
members_df.isnull().sum()
members_df.dropna(inplace=True)

In [12]:
members_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   member_id           600 non-null    str
 1   member_name         600 non-null    str
 2   gender              600 non-null    str
 3   age                 600 non-null    int64
 4   membership_type     600 non-null    str
 5   preferred_facility  600 non-null    str
 6   join_date           600 non-null    str
 7   expiry_date         600 non-null    str
 8   status              600 non-null    str
dtypes: int64(1), str(8)
memory usage: 42.3 KB

In [13]:
members_df['join_date'] = pd.to_datetime(members_df['join_date'])

In [14]:
members_df['expiry_date'] = pd.to_datetime(members_df['expiry_date'])

In [15]:
members_df[ members_df['age'] < 0]

Empty DataFrame
Columns: [member_id, member_name, gender, age, membership_type, preferred_facility, join_date, expiry_date, status]
Index: []

In [16]:
members_df.drop_duplicates(inplace=True)

In [17]:
members_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   member_id           600 non-null    str
 1   member_name         600 non-null    str
 2   gender              600 non-null    str
 3   age                 600 non-null    int64
 4   membership_type     600 non-null    str
 5   preferred_facility  600 non-null    str
 6   join_date           600 non-null    datetime64[us]
 7   expiry_date         600 non-null    datetime64[us]
 8   status              600 non-null    str
dtypes: datetime64[us](2), int64(1), str(6)
memory usage: 42.3 KB

In [22]:
cols_str = [col for col in members_df.columns if members_df[col].dtype in ["object", "string"]]

In [23]:
for col in cols_str:
    members_df[col] = members_df[col].astype('str').str.strip()

In [24]:
members_df['gender'].value_counts()

gender
Male      338
Female    261
female      1
Name: count, dtype: int64

In [25]:
members_df

,member_id,member_name,gender,age,membership_type,preferred_facility,join_date,expiry_date,status
0,M00001,Member 001,Male,39,Annual,Swimming Pool,2025-04-13,2026-04-13,Expired
1,M00002,Member 002,Male,30,Annual,Swimming Pool,2026-03-12,2027-03-12,Active
2,M00003,Member 003,Female,53,Monthly,Basketball,2025-09-28,2025-10-28,Expired
3,M00004,Member 004,Female,23,Monthly,Basketball,2025-04-17,2025-05-17,Expired
4,M00005,Member 005,Female,20,Monthly,Basketball,2025-03-13,2025-04-12,Expired
...,...,...,...,...,...,...,...,...,...
595,M00596,Member 596,Female,41,Monthly,Swimming Pool,2025-08-05,2025-09-04,Expired
596,M00597,Member 597,Female,23,Monthly,Badminton,2026-04-06,2026-05-06,Expired
597,M00598,Member 598,Female,63,Quarterly,Badminton,2025-04-15,2025-07-14,Expired
598,M00599,Member 599,Female,17,Monthly,Football,2025-04-09,2025-05-09,Expired
599,M00600,Member 600,Male,21,Annual,Football,2026-05-26,2027-05-26,Active

In [26]:
cols_lowercase = ['gender','membership_type' , 'preferred_facility','status']
for col in cols_lowercase:
    members_df[col] = members_df[col].apply(lambda x :x.lower())

In [27]:
members_df['membership_type'].value_counts()

membership_type
monthly      341
quarterly    156
annual       103
Name: count, dtype: int64

In [28]:
members_df['preferred_facility'].value_counts()

preferred_facility
badminton        137
basketball       124
football         124
gym              120
swimming pool     95
Name: count, dtype: int64

In [29]:
# members_df.loc [ members_df['preferred_facility'] == 'swimming pool', 'preferred_facility'] = 'Swimming Pool'

In [30]:
members_df['status'].value_counts()

status
expired    505
active      95
Name: count, dtype: int64

In [32]:
payments_df = pd.read_csv('data/raw/payments.csv')

In [33]:
merged_payments  = payments_df.merge(members_df,on='member_id' , how='inner')

In [34]:
merged_payments[['member_id','payment_date', 'amount_pkr','payment_type','payment_status',
    'membership_type','preferred_facility']]

,member_id,payment_date,amount_pkr,payment_type,payment_status,membership_type,preferred_facility
0,M00001,2026-06-17,30000.0,Membership Fee,Paid,annual,swimming pool
1,M00001,2026-04-28,30000.0,Registration,Paid,annual,swimming pool
2,M00001,2026-03-07,3500.0,Membership Fee,Paid,annual,swimming pool
3,M00002,2026-07-27,9000.0,Renewal,Paid,annual,swimming pool
4,M00002,2026-04-29,9000.0,Membership Fee,Paid,annual,swimming pool
...,...,...,...,...,...,...,...
1224,M00006,2026-06-24,30000.0,Membership Fee,Paid,monthly,swimming pool
1225,M00006,2026-07-10,30000.0,Renewal,Paid,monthly,swimming pool
1226,M00007,2026-04-20,9000.0,Membership Fee,Paid,monthly,badminton
1227,M00008,2026-05-20,3500.0,Renewal,Paid,monthly,football
1228,M00008,2026-08-16,9000.0,Renewal,Paid,monthly,football

In [35]:
merged_payments.groupby(['payment_type','membership_type', 'preferred_facility'])['amount_pkr'].mean()

payment_type    membership_type  preferred_facility
Membership Fee  annual           badminton             11833.333333
                                 basketball            10764.705882
                                 football              18812.500000
                                 gym                   18468.750000
                                 swimming pool         10633.333333
                monthly          badminton             15122.222222
                                 basketball            12957.446809
                                 football              13024.390244
                                 gym                   14812.500000
                                 swimming pool         12702.127660
                quarterly        badminton             13080.000000
                                 basketball            14732.142857
                                 football              13650.000000
                                 gym                   15156.250000
                                 swimming pool         11318.181818
Registration    annual           badminton             11105.263158
                                 basketball            15807.692308
                                 football              12388.888889
                                 gym                   21777.777778
                                 swimming pool         21863.636364
                monthly          badminton             12404.761905
                                 basketball            14391.304348
                                 football              15279.069767
                                 gym                   13454.545455
                                 swimming pool         12455.882353
                quarterly        badminton             16032.258065
                                 basketball            15166.666667
                                 football              11477.272727
                                 gym                   18605.263158
                                 swimming pool         10937.500000
Renewal         annual           badminton             10666.666667
                                 basketball            20363.636364
                                 football              13843.750000
                                 gym                   14187.500000
                                 swimming pool         12400.000000
                monthly          badminton             12215.517241
                                 basketball            12879.032258
                                 football              14764.150943
                                 gym                   14895.348837
                                 swimming pool         14655.555556
                quarterly        badminton             10037.037037
                                 basketball            13388.888889
                                 football              14119.047619
                                 gym                   13300.000000
                                 swimming pool         11411.764706
Name: amount_pkr, dtype: float64

In [36]:
pivot_df = merged_payments.pivot_table(
    values='member_id',   # The data you want to aggregate
    index='preferred_facility',      # Rows of the pivot table
    columns=['membership_type','payment_type'],    # Columns of the pivot table
    aggfunc='count',             # Aggregation (mean, sum, count, max, etc.)
    fill_value=0               # Replace missing values/NaNs
)
pivot_df

membership_type            annual                             monthly  \
payment_type       Membership Fee Registration Renewal Membership Fee
preferred_facility
badminton                      18           19      18             45
basketball                     17           13      11             47
football                        8           18      16             41
gym                            16            9      16             40
swimming pool                  15           11      15             47

membership_type                              quarterly
payment_type       Registration Renewal Membership Fee Registration Renewal
preferred_facility
badminton                    42      58             25           31      27
basketball                   46      63             28           21      27
football                     43      53             20           22      21
gym                          44      43             16           19      25
swimming pool                34      45             11            8      17

In [37]:
payments_df.drop_duplicates(inplace=True)

In [38]:
payments_df.dropna(inplace=True)

In [39]:


cols_lowercase = ['payment_type', 'payment_status']

for col in cols_lowercase:
    payments_df[col] = payments_df[col].apply(lambda x :x.lower())

In [40]:
pd.set_option('display.max_rows', None)

In [41]:
payments_df['payment_status'].value_counts()

payment_status
paid    1209
Name: count, dtype: int64

In [42]:
payments_df['payment_type'].value_counts()

payment_type
renewal           446
membership fee    385
registration      378
Name: count, dtype: int64

In [43]:
payments_df['amount_pkr'].value_counts()

amount_pkr
3500.0     421
9000.0     401
30000.0    387
Name: count, dtype: int64

In [44]:
payments_df

     member_id payment_date  amount_pkr    payment_type payment_status
0       M00001   2026-06-17     30000.0  membership fee           paid
1       M00001   2026-04-28     30000.0    registration           paid
2       M00001   2026-03-07      3500.0  membership fee           paid
3       M00002   2026-07-27      9000.0         renewal           paid
4       M00002   2026-04-29      9000.0  membership fee           paid
5       M00003   2026-06-08     30000.0         renewal           paid
6       M00003   2026-04-18      3500.0         renewal           paid
7       M00003   2026-07-14      3500.0         renewal           paid
9       M00004   2026-03-28      3500.0         renewal           paid
10      M00004   2026-02-19      9000.0  membership fee           paid
11      M00005   2026-02-21      9000.0  membership fee           paid
12      M00005   2026-04-10      9000.0  membership fee           paid
13      M00005   2026-03-25      3500.0    registration           paid
14      M00006   2026-01-06      3500.0  membership fee           paid
15      M00006   2026-06-24     30000.0  membership fee           paid
16      M00006   2026-07-10     30000.0         renewal           paid
17      M00007   2026-04-20      9000.0  membership fee           paid
18      M00008   2026-05-20      3500.0         renewal           paid
19      M00008   2026-08-16      9000.0         renewal           paid
20      M00008   2026-05-14     30000.0         renewal           paid
21      M00009   2026-06-03      3500.0  membership fee           paid
22      M00010   2026-06-14      9000.0    registration           paid
23      M00010   2026-03-09      3500.0  membership fee           paid
24      M00011   2026-04-17      9000.0         renewal           paid
25      M00011   2026-04-15      9000.0         renewal           paid
26      M00012   2026-08-29      9000.0  membership fee           paid
27      M00012   2026-08-03     30000.0         renewal           paid
28      M00012   2026-07-17     30000.0  membership fee           paid
29      M00013   2026-02-21      9000.0         renewal           paid
30      M00014   2026-04-30      3500.0         renewal           paid
31      M00014   2026-04-16      9000.0  membership fee           paid
32      M00015   2026-08-28      3500.0  membership fee           paid
33      M00015   2026-04-07     30000.0         renewal           paid
34      M00015   2026-08-01     30000.0    registration           paid
35      M00016   2026-07-26     30000.0         renewal           paid
36      M00016   2026-08-05     30000.0    registration           paid
37      M00017   2026-07-02      9000.0  membership fee           paid
38      M00017   2026-08-01      9000.0  membership fee           paid
39      M00017   2026-05-22      9000.0    registration           paid
40      M00018   2026-02-24      9000.0    registration           paid
41      M00018   2026-04-15     30000.0    registration           paid
42      M00019   2026-05-22     30000.0    registration           paid
43      M00020   2026-02-20     30000.0  membership fee           paid
44      M00020   2026-03-04      9000.0    registration           paid
45      M00021   2026-05-12     30000.0  membership fee           paid
46      M00021   2026-03-16      3500.0         renewal           paid
47      M00021   2026-02-21      3500.0         renewal           paid
48      M00022   2026-08-27      3500.0  membership fee           paid
49      M00023   2026-06-16      3500.0         renewal           paid
50      M00023   2026-08-02      3500.0    registration           paid
51      M00023   2026-07-18      9000.0  membership fee           paid
52      M00024   2026-04-24      3500.0         renewal           paid
53      M00024   2026-02-01     30000.0    registration           paid
54      M00025   2026-07-16      9000.0         renewal           paid
55      M00026   2026-01-07      9000.0         renewal           paid
56      M00026   2026-01-05      9000.0  membership fee           paid
57      M00026   2026-04-25      3500.0    registration           paid
58      M00027   2026-04-14      3500.0         renewal           paid
59      M00028   2026-07-05      3500.0    registration           paid
60      M00028   2026-05-25      9000.0    registration           paid
61      M00028   2026-08-31      9000.0  membership fee           paid
62      M00029   2026-07-16     30000.0  membership fee           paid
63      M00029   2026-02-16     30000.0         renewal           paid
64      M00030   2026-02-17      9000.0    registration           paid
65      M00030   2026-04-29      9000.0         renewal           paid
66      M00030   2026-05-29      9000.0    registration           paid
67      M00031   2026-01-28      3500.0    registration           paid
68      M00032   2026-05-25      9000.0         renewal           paid
69      M00032   2026-04-08     30000.0  membership fee           paid
70      M00033   2026-02-23      3500.0         renewal           paid
71      M00033   2026-06-11      3500.0  membership fee           paid
72      M00033   2026-03-16     30000.0  membership fee           paid
73      M00034   2026-04-01      9000.0         renewal           paid
74      M00035   2026-01-02      3500.0         renewal           paid
75      M00035   2026-06-26      3500.0         renewal           paid
76      M00036   2026-08-01      3500.0  membership fee           paid
77      M00036   2026-03-24     30000.0  membership fee           paid
78      M00036   2026-01-10      3500.0  membership fee           paid
79      M00037   2026-02-01     30000.0  membership fee           paid
80      M00037   2026-04-14      9000.0  membership fee           paid
81      M00038   2026-04-23     30000.0  membership fee           paid
82      M00038   2026-05-19      3500.0    registration           paid
83      M00039   2026-04-13     30000.0    registration           paid
84      M00040   2026-05-25     30000.0  membership fee           paid
85      M00040   2026-06-17      9000.0  membership fee           paid
86      M00040   2026-07-16      3500.0  membership fee           paid
87      M00041   2026-07-19      9000.0         renewal           paid
88      M00041   2026-02-04     30000.0         renewal           paid
89      M00042   2026-06-29      9000.0         renewal           paid
90      M00042   2026-06-28      9000.0  membership fee           paid
91      M00043   2026-02-02      3500.0  membership fee           paid
92      M00044   2026-06-04     30000.0  membership fee           paid
93      M00045   2026-05-26     30000.0    registration           paid
94      M00045   2026-03-04     30000.0         renewal           paid
95      M00046   2026-04-02      9000.0  membership fee           paid
96      M00047   2026-05-16      9000.0    registration           paid
97      M00048   2026-05-04      3500.0    registration           paid
98      M00048   2026-04-02      9000.0    registration           paid
99      M00048   2026-08-25      3500.0         renewal           paid
100     M00049   2026-02-04      3500.0  membership fee           paid
101     M00049   2026-05-31      9000.0         renewal           paid
102     M00049   2026-07-23      3500.0         renewal           paid
103     M00050   2026-05-05     30000.0  membership fee           paid
104     M00050   2026-05-16      9000.0    registration           paid
105     M00051   2026-05-08     30000.0  membership fee           paid
106     M00051   2026-04-27      3500.0         renewal           paid
107     M00051   2026-04-08      9000.0         renewal           paid
108     M00052   2026-04-14      9000.0    registration           paid
109     M00053   2026-02-25      9000.0         renewal           paid
110     M00053   2026-01-28      3500.0         renewal           paid
111     M00054   2026-04-02     30000.0  membership fee           paid
112     M00055   2026-05-07      3500.0  membership fee           paid
113     M00056   2026-01-16      3500.0    registration           paid
114     M00056   2026-05-15      9000.0         renewal           paid
115     M00057   2026-02-10      3500.0    registration           paid
116     M00057   2026-03-12      3500.0  membership fee           paid
117     M00057   2026-08-10      9000.0    registration           paid
118     M00058   2026-05-31      9000.0         renewal           paid
119     M00058   2026-05-06      3500.0  membership fee           paid
120     M00059   2026-02-09     30000.0    registration           paid
121     M00060   2026-03-11      9000.0  membership fee           paid
122     M00060   2026-02-15     30000.0    registration           paid
123     M00060   2026-05-18      9000.0    registration           paid
124     M00061   2026-03-21      3500.0  membership fee           paid
125     M00062   2026-04-03      9000.0    registration           paid
126     M00063   2026-02-28      9000.0         renewal           paid
127     M00063   2026-01-17      9000.0  membership fee           paid
128     M00063   2026-03-19      3500.0         renewal           paid
129     M00064   2026-07-19      9000.0         renewal           paid
130     M00064   2026-04-08      9000.0         renewal           paid
131     M00065   2026-04-21      3500.0  membership fee           paid
132     M00065   2026-05-31      3500.0         renewal           paid
133     M00066   2026-08-16      9000.0    registration           paid
134     M00066   2026-06-28      9000.0  membership fee           paid
135     M00066   2026-01-14      9000.0  membership fee           paid
136     M00067   2026-07-11      9000.0    registration           paid
137     M00067   2026-07-25      9000.0  membership fee           paid
138     M00068   2026-06-16      3500.0    registration           paid
139     M00069   2026-02-12      3500.0         renewal           paid
140     M00069   2026-08-15     30000.0  membership fee           paid
141     M00069   2026-04-18      3500.0    registration           paid
142     M00070   2026-01-16     30000.0         renewal           paid
143     M00070   2026-02-19     30000.0         renewal           paid
144     M00070   2026-01-05     30000.0  membership fee           paid
145     M00071   2026-03-28     30000.0  membership fee           paid
146     M00071   2026-07-12     30000.0  membership fee           paid
147     M00071   2026-08-13      9000.0    registration           paid
148     M00072   2026-05-07     30000.0    registration           paid
149     M00072   2026-04-30      3500.0    registration           paid
150     M00073   2026-06-02      9000.0    registration           paid
151     M00074   2026-08-21      9000.0    registration           paid
152     M00075   2026-01-20     30000.0    registration           paid
153     M00075   2026-02-19      9000.0         renewal           paid
154     M00075   2026-08-31     30000.0         renewal           paid
155     M00076   2026-01-07      3500.0  membership fee           paid
156     M00077   2026-01-05     30000.0    registration           paid
157     M00077   2026-06-08      3500.0  membership fee           paid
158     M00077   2026-01-11      9000.0  membership fee           paid
159     M00078   2026-01-26     30000.0    registration           paid
160     M00078   2026-05-31      9000.0    registration           paid
161     M00078   2026-05-29      9000.0    registration           paid
162     M00079   2026-04-19      9000.0         renewal           paid
163     M00079   2026-04-16      9000.0         renewal           paid
164     M00079   2026-07-18      3500.0  membership fee           paid
165     M00080   2026-03-10      9000.0    registration           paid
166     M00080   2026-03-05      3500.0         renewal           paid
167     M00081   2026-04-05     30000.0    registration           paid
168     M00081   2026-07-06     30000.0         renewal           paid
169     M00082   2026-01-27      3500.0         renewal           paid
170     M00082   2026-06-22     30000.0         renewal           paid
171     M00082   2026-03-18      3500.0  membership fee           paid
172     M00083   2026-07-08     30000.0         renewal           paid
173     M00083   2026-07-24     30000.0         renewal           paid
174     M00084   2026-06-11      3500.0         renewal           paid
175     M00085   2026-02-22      3500.0  membership fee           paid
176     M00085   2026-07-05     30000.0    registration           paid
177     M00086   2026-06-26      9000.0         renewal           paid
178     M00086   2026-01-29      3500.0         renewal           paid
179     M00087   2026-01-09      3500.0    registration           paid
180     M00087   2026-08-25      3500.0         renewal           paid
181     M00088   2026-05-18      3500.0  membership fee           paid
182     M00088   2026-01-20     30000.0  membership fee           paid
183     M00088   2026-01-28     30000.0         renewal           paid
184     M00089   2026-05-09     30000.0         renewal           paid
185     M00089   2026-05-02     30000.0    registration           paid
186     M00089   2026-06-23     30000.0         renewal           paid
187     M00090   2026-05-31      9000.0    registration           paid
188     M00090   2026-04-30      3500.0    registration           paid
189     M00090   2026-08-04     30000.0         renewal           paid
190     M00091   2026-07-04      3500.0    registration           paid
191     M00092   2026-01-15      3500.0         renewal           paid
192     M00092   2026-02-06     30000.0    registration           paid
193     M00093   2026-07-29      9000.0  membership fee           paid
194     M00093   2026-07-18     30000.0         renewal           paid
195     M00094   2026-02-18      9000.0    registration           paid
196     M00094   2026-06-22      3500.0    registration           paid
197     M00094   2026-06-15      3500.0    registration           paid
198     M00095   2026-05-31      9000.0         renewal           paid
199     M00095   2026-06-30     30000.0  membership fee           paid
200     M00095   2026-02-05      9000.0         renewal           paid
201     M00096   2026-04-12     30000.0  membership fee           paid
202     M00097   2026-01-23      9000.0  membership fee           paid
203     M00098   2026-04-25     30000.0    registration           paid
204     M00099   2026-02-23     30000.0    registration           paid
205     M00099   2026-07-15      3500.0         renewal           paid
206     M00099   2026-07-19      3500.0         renewal           paid
207     M00100   2026-03-06     30000.0  membership fee           paid
208     M00100   2026-03-07      3500.0    registration           paid
209     M00100   2026-05-19      9000.0         renewal           paid
210     M00101   2026-06-12      3500.0    registration           paid
211     M00101   2026-07-10     30000.0    registration           paid
212     M00101   2026-01-23     30000.0         renewal           paid
213     M00102   2026-05-23      3500.0    registration           paid
214     M00102   2026-07-12      9000.0    registration           paid
215     M00102   2026-01-25     30000.0    registration           paid
216     M00103   2026-06-21      3500.0    registration           paid
217     M00103   2026-02-15     30000.0    registration           paid
218     M00104   2026-03-25     30000.0    registration           paid
219     M00104   2026-07-17      3500.0         renewal           paid
220     M00105   2026-02-19     30000.0  membership fee           paid
221     M00106   2026-02-17      3500.0  membership fee           paid
222     M00106   2026-04-23      3500.0    registration           paid
223     M00106   2026-08-01      3500.0         renewal           paid
224     M00107   2026-04-16     30000.0         renewal           paid
225     M00107   2026-08-16     30000.0  membership fee           paid
226     M00108   2026-02-13     30000.0  membership fee           paid
227     M00108   2026-07-10      3500.0  membership fee           paid
228     M00108   2026-05-06      3500.0  membership fee           paid
229     M00109   2026-07-11      3500.0         renewal           paid
230     M00109   2026-07-01      9000.0         renewal           paid
231     M00110   2026-05-03      9000.0  membership fee           paid
232     M00110   2026-02-20      9000.0  membership fee           paid
233     M00111   2026-05-15     30000.0    registration           paid
234     M00112   2026-06-20      3500.0    registration           paid
235     M00112   2026-03-03      9000.0         renewal           paid
236     M00113   2026-06-18      3500.0         renewal           paid
237     M00114   2026-02-21      3500.0    registration           paid
238     M00114   2026-08-06      9000.0    registration           paid
239     M00114   2026-05-11      3500.0         renewal           paid
240     M00115   2026-06-22      3500.0  membership fee           paid
241     M00115   2026-07-29      9000.0  membership fee           paid
242     M00115   2026-05-05      9000.0    registration           paid
243     M00116   2026-08-14     30000.0         renewal           paid
244     M00116   2026-04-17      3500.0  membership fee           paid
245     M00116   2026-02-21      3500.0         renewal           paid
246     M00117   2026-07-05     30000.0         renewal           paid
247     M00118   2026-01-04      3500.0    registration           paid
248     M00119   2026-08-11      9000.0         renewal           paid
249     M00119   2026-01-11      3500.0  membership fee           paid
250     M00119   2026-05-04     30000.0         renewal           paid
251     M00120   2026-07-08     30000.0  membership fee           paid
252     M00120   2026-07-09      3500.0    registration           paid
253     M00120   2026-03-30      9000.0  membership fee           paid
254     M00121   2026-04-28      3500.0         renewal           paid
255     M00121   2026-07-27     30000.0  membership fee           paid
256     M00122   2026-03-11      9000.0         renewal           paid
257     M00122   2026-03-08      3500.0         renewal           paid
258     M00123   2026-06-07     30000.0    registration           paid
259     M00123   2026-01-01      9000.0  membership fee           paid
260     M00124   2026-07-19     30000.0    registration           paid
261     M00125   2026-05-16     30000.0         renewal           paid
262     M00126   2026-07-19      3500.0         renewal           paid
263     M00126   2026-03-29      3500.0    registration           paid
264     M00126   2026-06-24      9000.0    registration           paid
265     M00127   2026-03-24      3500.0    registration           paid
266     M00127   2026-06-19      9000.0  membership fee           paid
267     M00128   2026-06-20     30000.0  membership fee           paid
268     M00128   2026-04-13     30000.0         renewal           paid
269     M00128   2026-08-14      9000.0    registration           paid
270     M00129   2026-02-22     30000.0    registration           paid
271     M00129   2026-02-02     30000.0         renewal           paid
272     M00130   2026-01-22      9000.0    registration           paid
273     M00130   2026-06-22     30000.0    registration           paid
274     M00130   2026-07-23      3500.0         renewal           paid
275     M00131   2026-06-29      9000.0    registration           paid
276     M00131   2026-07-29      3500.0         renewal           paid
277     M00132   2026-08-29      3500.0         renewal           paid
278     M00132   2026-02-28     30000.0         renewal           paid
279     M00133   2026-01-02      9000.0  membership fee           paid
280     M00134   2026-07-06      3500.0    registration           paid

In [46]:
attendence_df = pd.read_csv('data/raw/attendance.csv')

In [47]:
attendence_df.drop_duplicates(inplace=True)
attendence_df.dropna(inplace=True)

In [48]:
attendence_df [ attendence_df['member_id'] == 'M00115' ]

     member_id attendance_date       facility check_in_time
0       M00115      2026-01-07      Badminton         13:15
1942    M00115      2026-01-23      Badminton         12:00
2640    M00115      2026-07-21  Swimming Pool         19:45
2738    M00115      2026-07-13  Swimming Pool         21:00
2961    M00115      2026-02-28            Gym         18:15
3234    M00115      2026-03-28       Football         14:30
3843    M00115      2026-01-22     Basketball         06:30
3933    M00115      2026-02-05  Swimming Pool         10:45
4603    M00115      2026-04-08            Gym         10:00
5087    M00115      2026-05-28  Swimming Pool         18:00
6105    M00115      2026-06-06     Basketball         20:45
6611    M00115      2026-08-12     Basketball         18:15
7109    M00115      2026-02-17            Gym         17:45
7923    M00115      2026-07-25       Football         14:00
8618    M00115      2026-02-20      Badminton         19:00

In [49]:
attendence_df['facility'] = attendence_df['facility'].apply(lambda x :x.lower())

In [50]:
attendence_df['facility'].value_counts()

facility
swimming pool     1861
badminton         1842
football          1804
basketball        1756
gym               1738
swimming pool        1
Name: count, dtype: int64

In [51]:
attendence_df['attendance_date'] = pd.to_datetime(attendence_df['attendance_date'])

In [121]:
attendence_df

     member_id attendance_date        facility check_in_time
0       M00115      2026-01-07       badminton         13:15
1       M00143      2026-07-08             gym         08:45
2       M00033      2026-01-08             gym         12:15
3       M00518      2026-06-04             gym         12:45
4       M00226      2026-04-25        football         14:00
5       M00164      2026-06-28      basketball         16:30
6       M00160      2026-02-25       badminton         09:00
7       M00390      2026-01-25       badminton         17:30
8       M00045      2026-07-06      basketball         09:45
9       M00081      2026-05-22       badminton         17:15
10      M00072      2026-01-12             gym         15:00
11      M00239      2026-08-10             gym         18:30
12      M00465      2026-06-12       badminton         11:30
13      M00364      2026-02-23       badminton         08:15
14      M00547      2026-07-06   swimming pool         11:45
15      M00389      2026-03-11        football         13:30
16      M00058      2026-02-28             gym         16:45
17      M00275      2026-01-17   swimming pool         16:15
18      M00512      2026-04-12      basketball         10:30
19      M00143      2026-03-05        football         14:45
20      M00598      2026-04-13       badminton         13:15
21      M00522      2026-05-07             gym         07:00
22      M00157      2026-06-10   swimming pool         19:00
23      M00395      2026-04-08        football         20:30
24      M00567      2026-08-09             gym         09:30
25      M00349      2026-01-29  swimming pool          19:15
26      M00465      2026-01-01       badminton         11:00
27      M00306      2026-08-04        football         12:15
28      M00383      2026-07-15   swimming pool         06:30
29      M00501      2026-01-05             gym         17:30
30      M00246      2026-01-15   swimming pool         08:00
31      M00498      2026-07-28             gym         10:15
32      M00487      2026-08-31        football         11:30
33      M00541      2026-08-12        football         19:15
34      M00553      2026-07-13   swimming pool         15:45
35      M00383      2026-04-23        football         20:00
36      M00254      2026-02-27             gym         16:00
37      M00568      2026-02-28        football         13:00
38      M00073      2026-07-01             gym         13:00
39      M00033      2026-08-09       badminton         08:15
40      M00286      2026-06-21      basketball         12:15
41      M00585      2026-05-28      basketball         13:45
42      M00417      2026-02-18             gym         09:45
43      M00363      2026-04-19      basketball         20:00
44      M00101      2026-01-16      basketball         16:00
45      M00255      2026-02-19   swimming pool         20:15
46      M00433      2026-02-16       badminton         20:15
47      M00078      2026-04-24        football         09:00
48      M00554      2026-08-03             gym         08:15
49      M00171      2026-04-15      basketball         21:15
50      M00411      2026-08-20             gym         11:45
51      M00003      2026-04-10       badminton         20:30
52      M00434      2026-06-28        football         21:15
53      M00195      2026-03-17   swimming pool         07:00
54      M00322      2026-01-15             gym         21:15
55      M00059      2026-05-11             gym         11:00
56      M00070      2026-06-22   swimming pool         18:00
57      M00584      2026-03-05        football         07:00
58      M00430      2026-06-18        football         16:30
59      M00210      2026-06-21       badminton         13:30
60      M00406      2026-02-03       badminton         20:30
61      M00075      2026-01-03      basketball         09:00
62      M00551      2026-02-24        football         14:15
63      M00358      2026-08-14             gym         13:30
64      M00292      2026-02-10      basketball         15:00
65      M00568      2026-03-18             gym         10:30
66      M00119      2026-08-16             gym         10:30
67      M00289      2026-06-04   swimming pool         16:15
68      M00271      2026-05-10      basketball         14:00
69      M00095      2026-06-12      basketball         14:00
70      M00004      2026-03-27   swimming pool         14:15
71      M00453      2026-05-22      basketball         06:00
72      M00078      2026-08-30   swimming pool         07:30
73      M00597      2026-05-22   swimming pool         19:15
74      M00043      2026-03-20       badminton         07:30
75      M00216      2026-06-24   swimming pool         09:30
76      M00574      2026-08-15      basketball         10:15
77      M00167      2026-07-24   swimming pool         19:00
78      M00184      2026-07-08       badminton         19:15
79      M00274      2026-02-10             gym         18:00
80      M00482      2026-02-26   swimming pool         20:30
81      M00313      2026-07-30   swimming pool         13:00
82      M00198      2026-04-13       badminton         14:00
83      M00286      2026-03-31        football         18:30
84      M00029      2026-01-30       badminton         11:30
85      M00040      2026-01-28        football         19:30
86      M00322      2026-04-22        football         09:45
87      M00591      2026-02-18       badminton         07:45
88      M00002      2026-05-14        football         12:30
89      M00442      2026-01-18       badminton         16:00
90      M00308      2026-05-10       badminton         19:30
91      M00413      2026-06-28       badminton         10:15
92      M00431      2026-06-20      basketball         11:30
93      M00416      2026-05-21             gym         15:30
94      M00216      2026-04-21        football         16:45
95      M00453      2026-04-24   swimming pool         21:15
96      M00087      2026-03-14        football         16:00
97      M00241      2026-06-22       badminton         13:15
98      M00151      2026-01-07             gym         13:45
99      M00075      2026-04-27      basketball         12:45
100     M00507      2026-04-13   swimming pool         10:00
101     M00110      2026-07-19      basketball         13:15
102     M00531      2026-04-29             gym         13:00
103     M00468      2026-02-04      basketball         16:45
104     M00517      2026-04-20        football         20:15
105     M00487      2026-04-26       badminton         13:30
106     M00534      2026-05-05   swimming pool         14:45
107     M00080      2026-07-02       badminton         13:30
108     M00344      2026-03-23        football         08:15
109     M00155      2026-03-01      basketball         10:15
110     M00066      2026-04-17      basketball         16:45
111     M00426      2026-01-16   swimming pool         19:45
112     M00599      2026-08-31             gym         18:45
113     M00007      2026-08-30       badminton         15:45
114     M00430      2026-05-18        football         13:45
115     M00225      2026-03-11      basketball         21:00
116     M00399      2026-03-28      basketball         11:45
117     M00131      2026-06-09        football         06:45
118     M00578      2026-06-19             gym         08:45
119     M00139      2026-08-10      basketball         11:00
120     M00267      2026-04-08       badminton         12:45
121     M00335      2026-03-28      basketball         14:45
122     M00259      2026-08-02             gym         21:00
123     M00553      2026-01-14       badminton         13:00
124     M00042      2026-07-13             gym         13:15
125     M00021      2026-06-09   swimming pool         13:15
126     M00485      2026-06-21             gym         12:45
127     M00263      2026-07-16       badminton         11:00
128     M00168      2026-03-21             gym         06:30
129     M00590      2026-06-23      basketball         18:15
130     M00078      2026-06-01   swimming pool         09:30
131     M00124      2026-07-23        football         07:30
132     M00546      2026-04-20       badminton         08:30
133     M00013      2026-08-06      basketball         21:00
134     M00444      2026-04-03      basketball         10:45
135     M00181      2026-07-07        football         14:45
136     M00477      2026-04-22        football         14:30
137     M00252      2026-08-01             gym         14:45
138     M00250      2026-07-12      basketball         18:30
139     M00030      2026-05-07       badminton         11:45
140     M00218      2026-04-01       badminton         16:30
141     M00283      2026-05-23             gym         12:00
142     M00248      2026-07-04      basketball         21:15
143     M00488      2026-06-15      basketball         20:00
144     M00096      2026-03-17   swimming pool         18:15
145     M00314      2026-06-19        football         17:45
146     M00567      2026-05-16       badminton         19:30
147     M00361      2026-06-29      basketball         14:30
148     M00258      2026-03-01             gym         12:30
149     M00123      2026-07-10        football         11:15
150     M00222      2026-07-09      basketball         14:30
151     M00103      2026-08-02   swimming pool         15:15
152     M00370      2026-02-15       badminton         06:15
153     M00281      2026-01-12             gym         15:15
154     M00503      2026-01-27             gym         15:45
155     M00491      2026-04-23       badminton         11:00
156     M00259      2026-08-29      basketball         09:00
157     M00411      2026-05-06             gym         07:15
158     M00153      2026-07-27        football         15:00
159     M00255      2026-01-31        football         19:15
160     M00536      2026-04-08      basketball         20:30
161     M00440      2026-03-20        football         07:00
162     M00213      2026-06-10   swimming pool         14:00
163     M00161      2026-03-03   swimming pool         08:15
164     M00003      2026-04-15      basketball         21:30
165     M00034      2026-03-01       badminton         15:45
166     M00073      2026-06-25   swimming pool         14:15
167     M00436      2026-01-30        football         13:15
168     M00273      2026-07-31   swimming pool         08:00
169     M00170      2026-07-22       badminton         15:45
170     M00128      2026-04-30       badminton         18:30
171     M00513      2026-05-19      basketball         20:00
172     M00041      2026-08-16      basketball         16:30
173     M00027      2026-01-24   swimming pool         06:30
174     M00591      2026-01-11   swimming pool         21:45
175     M00285      2026-02-16        football         19:45
176     M00094      2026-05-01       badminton         19:30
177     M00329      2026-06-21             gym         11:30
178     M00422      2026-06-27      basketball         15:45
179     M00564      2026-01-10      basketball         08:30
180     M00259      2026-03-24             gym         18:00
181     M00556      2026-04-29      basketball         07:15
182     M00531      2026-04-03        football         21:45
183     M00053      2026-02-22       badminton         10:30
184     M00449      2026-08-14      basketball         09:00
185     M00246      2026-07-01   swimming pool         15:00
186     M00566      2026-04-15             gym         13:00
187     M00473      2026-08-31             gym         10:45
188     M00299      2026-05-11       badminton         19:45
189     M00484      2026-03-04      basketball         10:45
190     M00196      2026-08-24        football         10:00
191     M00283      2026-07-17      basketball         16:30
192     M00003      2026-03-14       badminton         21:15
193     M00458      2026-05-18      basketball         17:30
194     M00566      2026-07-15        football         18:45
195     M00330      2026-08-11   swimming pool         13:45
196     M00240      2026-08-08      basketball         07:30
197     M00485      2026-06-30      basketball         18:15
198     M00508      2026-01-10   swimming pool         16:00
199     M00451      2026-01-26        football         20:00
200     M00148      2026-04-15   swimming pool         08:45
201     M00272      2026-03-28        football         18:00
202     M00337      2026-08-07        football         18:30
203     M00500      2026-08-12        football         07:00
204     M00241      2026-06-11       badminton         13:00
205     M00445      2026-01-26             gym         20:15
206     M00307      2026-08-20             gym         07:30
207     M00058      2026-03-17       badminton         17:45
208     M00150      2026-03-04        football         19:15
209     M00175      2026-02-14             gym         18:15
210     M00510      2026-08-22        football         10:15
211     M00473      2026-06-13       badminton         20:30
212     M00010      2026-08-19      basketball         15:15
213     M00076      2026-04-24       badminton         15:45
214     M00257      2026-04-27       badminton         12:45
215     M00495      2026-01-28   swimming pool         18:30
216     M00589      2026-03-17       badminton         06:45
217     M00282      2026-01-03        football         07:45
218     M00294      2026-07-18   swimming pool         17:15
219     M00195      2026-06-08       badminton         10:00
220     M00041      2026-03-21      basketball         07:30
221     M00135      2026-01-24       badminton         16:45
222     M00180      2026-02-21   swimming pool         17:30
223     M00169      2026-03-07      basketball         15:30
224     M00118      2026-04-30             gym         10:15
225     M00407      2026-08-05        football         17:00
226     M00405      2026-01-04       badminton         09:45
227     M00378      2026-06-22       badminton         18:30
228     M00111      2026-06-22   swimming pool         21:00
229     M00575      2026-03-25        football         13:00
230     M00476      2026-08-21       badminton         19:00
231     M00144      2026-01-12             gym         15:45
232     M00119      2026-01-25   swimming pool         10:45
233     M00465      2026-04-05        football         19:15
234     M00425      2026-06-17             gym         21:45
235     M00287      2026-01-09       badminton         12:45
236     M00456      2026-03-02       badminton         09:30
237     M00558      2026-08-19       badminton         07:45
238     M00283      2026-02-18             gym         20:00
239     M00218      2026-06-14        football         06:00
240     M00342      2026-03-04   swimming pool         12:00
241     M00568      2026-02-23        football         12:15
242     M00337      2026-07-18   swimming pool         06:30
243     M00149      2026-02-03        football         14:15
244     M00113      2026-06-19             gym         10:00
245     M00367      2026-07-22   swimming pool         16:00
246     M00179      2026-03-09             gym         10:45
247     M00539      2026-01-30             gym         21:45
248     M00371      2026-05-12        football         09:45
249     M00516      2026-02-26        football         07:30
250     M00470      2026-06-14             gym         07:45
251     M00412      2026-04-20             gym         21:45
252     M00076      2026-08-19             gym         16:15
253     M00068      2026-02-02       badminton         16:45
254     M00544      2026-03-17      basketball         19:00
255     M00118      2026-08-07        football         12:45
256     M00463      2026-08-16   swimming pool         19:30
257     M00465      2026-04-13      basketball         09:30
258     M00438      2026-03-22       badminton         17:15
259     M00486      2026-01-18             gym         08:00
260     M00443      2026-01-25       badminton         10:00
261     M00576      2026-05-24       badminton         09:45
262     M00363      2026-08-12      basketball         07:30
263     M00320      2026-04-01             gym         12:15
264     M00494      2026-02-27             gym         17:30
265     M00118      2026-07-15       badminton         13:45
266     M00575      2026-07-16        football         06:30
267     M00030      2026-02-16       badminton         15:30
268     M00360      2026-01-02   swimming pool         10:45
269     M00072      2026-02-06             gym         08:15
270     M00386      2026-04-18      basketball         16:15
271     M00379      2026-03-21       badminton         08:00
272     M00160      2026-02-10        football         07:00
273     M00279      2026-04-24      basketball         21:45
274     M00425      2026-03-11   swimming pool         09:30
275     M00441      2026-01-29       badminton         21:30
276     M00047      2026-02-26      basketball         07:00
277     M00210      2026-03-19   swimming pool         10:30
278     M00297      2026-03-25             gym         06:45
279     M00441      2026-02-14   swimming pool         18:15
280     M00513      2026-05-24       badminton         08:45
281     M00044      2026-04-22             gym         20:00
282     M00321      2026-05-28      basketball         18:45
283     M00297      2026-01-30      basketball         06:30
284     M00176      2026-07-25        football         20:30
285     M00091      2026-04-22             gym         13:45
286     M00411      2026-05-15             gym         18:30
287     M00348      2026-02-26       badminton         11:00
288     M00523      2026-06-12             gym         12:30
289     M00360      2026-07-06   swimming pool         13:00
290     M00150      2026-03-07   swimming pool         11:15
291     M00078      2026-02-15      basketball         20:45
292     M00579      2026-06-14        football         16:30
293     M00155      2026-04-23             gym         21:45
294     M00311      2026-07-23       badminton         07:30
295     M00520      2026-01-19       badminton         20:45
296     M00039      2026-01-15       badminton         15:00
297     M00093      2026-06-07        football         18:45
298     M00595      2026-05-22             gym         20:15
299     M00330      2026-06-04      basketball         10:00
300     M00462      2026-01-27       badminton         08:15
301     M00041      2026-03-05      basketball         20:15
302     M00373      2026-04-06       badminton         18:45
303     M00347      2026-06-23        football         07:30
304     M00068      2026-03-26             gym         18:30
305     M00259      2026-07-05        football         10:30
306     M00084      2026-05-30   swimming pool         17:30
307     M00402      2026-02-03        football         08:30
308     M00573      2026-04-07       badminton         10:00
309     M00434      2026-05-11       badminton         06:30
310     M00317      2026-02-16   swimming pool         16:45
311     M00197      2026-02-27   swimming pool         10:00
312     M00303      2026-08-05             gym         07:30
313     M00135      2026-06-02      basketball         10:15
314     M00186      2026-08-01        football         11:45
315     M00045      2026-04-16       badminton         13:45
316     M00292      2026-07-12      basketball         13:15
317     M00317      2026-07-27      basketball         12:30
318     M00585      2026-04-23      basketball         15:45
319     M00515      2026-05-16      basketball         11:15
320     M00142      2026-08-12       badminton         07:45
321     M00381      2026-05-22             gym         09:30
322     M00086      2026-07-15   swimming pool         14:45
323     M00526      2026-02-07      basketball         08:15
324     M00462      2026-08-15       badminton         06:45
325     M00055      2026-04-12        football         17:15

In [52]:
os.makedirs('data/processed', exist_ok=True)

In [123]:
facilities_df.to_csv('data/processed/facilities.csv')
members_df.to_csv('data/processed/members.csv')
payments_df.to_csv('data/processed/payments.csv')
attendence_df.to_csv('data/processed/attendance.csv')